In [3]:
import numpy as np
import pandas as pd

In [4]:
# Merging & Joining Data

df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [12]:
pd.merge(df_customers , df_orders , on='customer_id')
pd.merge(df_customers , df_orders , on='customer_id' , how='inner')
pd.merge(df_customers , df_orders , on='customer_id' , how='left')
pd.merge(df_customers , df_orders , on='customer_id' , how='right')
pd.merge(df_customers , df_orders , on='customer_id' , how='outer')

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [5]:
df_customers
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180